name: publish

on:
  push:

env:
  TAG_NAME: vulnivore:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Login to Google Artifact Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: asia-northeast1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GOOGLE_CLOUD_SA_KEY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          push: true
          tags: asia-northeast1-docker.pkg.dev/mztn-gcp-ops/service-images/${{ env.TAG_NAME }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_SA_KEY }}
          service_account: "vulnivore-deployer@mztn-gcp-ops.iam.gserviceaccount.com"

      - name: Deploy to Cloud Run
        run: |
          gcloud beta run deploy vulnivore \
            --image=asia-northeast1-docker.pkg.dev/mztn-gcp-ops/service-images/${{ env.TAG_NAME }} \
            --region=asia-northeast1 \
            --platform=managed \
            --allow-unauthenticated \
            --service-account=vulnivore@mztn-gcp-ops.iam.gserviceaccount.com
