name: publish

on:
  push:

env:
  TAG_NAME: vulnivore:${{ github.sha }}
  GCP_PROJECT_NAME: "mztn-gcp-ops"
  GCP_PROJECT_NUMBER: "687909555191"
  GCP_REGION: "asia-northeast1"
  GCP_REGISTRY: "asia-northeast1-docker.pkg.dev"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Login to Google Artifact Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.GCP_REGISTRY }}
          username: _json_key
          password: ${{ secrets.GOOGLE_CLOUD_SA_KEY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          push: true
          tags: ${{ env.GCP_REGISTRY }}/${{ env.GCP_PROJECT_NAME }}/service-images/${{ env.TAG_NAME }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_SA_KEY }}
          service_account: "vulnivore-deployer@${{ env.GCP_PROJECT_NAME }}.iam.gserviceaccount.com"

      - name: Deploy to Cloud Run
        run: |
          gcloud beta run deploy vulnivore \
            --image=${{ env.GCP_REGISTRY }}/${{ env.GCP_PROJECT_NAME }}/service-images/${{ env.TAG_NAME }} \
            --region=${{ env.GCP_REGION }} \
            --platform=managed \
            --allow-unauthenticated \
            --ingress=all \
            --set-env-vars "
              VULNIVORE_POLICY_DIR=/policy,
              VULNIVORE_LOG_FORMAT=json,
              VULNIVORE_GITHUB_APP_ID=417839,
              VULNIVORE_GITHUB_APP_INSTALLATION_ID=43608677,

              VULNIVORE_FIRESTORE_PROJECT_ID=${{ env.GCP_PROJECT_NAME }},
              VULNIVORE_FIRESTORE_COLLECTION=vulnivore
            " \
            --args serve \
            --set-secrets "
              VULNIVORE_GITHUB_APP_PRIVATE_KEY=projects/${{ env.GCP_PROJECT_NAME }}/secrets/VULNIVORE_GITHUB_APP_PRIVATE_KEY:latest,
              VULNIVORE_GITHUB_APP_SECRET=projects/${{ env.GCP_PROJECT_NAME }}/secrets/VULNIVORE_GITHUB_APP_SECRET:latest
            " \
            --service-account=vulnivore@${{ env.GCP_PROJECT_NAME }}.iam.gserviceaccount.com
